### ISSUE TITLE
0531 To-do

### ISSUE THREAD

**Issue by JayC1208** [vyongs/IMAKE#1]
- [x] 페인트 쓰러뜨리면 발자국
- [x] 바이러스 소리 확인 - setVolume function, int(W/2)
- [x] 불꽃놀이 소리 확인
- [x] 드로잉 소리 확인
- [ ] 풀 스크린에 맞춰서  사물 조절
- [x] firework, virus 대칭 - np.flip(frame, axis = 1) -> background, frame
- [x] 이미지 업로드하는 코드 삽입
- [x] 동물 얼굴 이미지 추가하기
- [x] 스코어 리턴하기
- [x] 1위 채크하고 등록하기
- [ ] 서버 qr 코드 되는지 확인하기 
- [x] 포스터 제작

**Comment by minie12** [comment]
- [x] 드로잉 안내장 코드 수정
- [x] 포스터 글 대략 작성
- [x] 포스터 구조도 생성
- [x] 포스터 개발 환경 이미지 생성

**Comment by minie12** [comment]
- [ ] 불꽃 파티클 제일 많이 터질때 or 제일 높게 갈 때 사진 찍기
